In [1]:
result=[]
for x in range(2000,3201):
    if (x%7==0) and (x%5!=0):
        result.append(x)
print(result)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


In [2]:
num = int(input("Enter the number :"))
factorial = 1 
if num < 0 :
    print("no factorial for negative numbers ")
if num == 0:
    print( "factorial of 0 is 1 ")
if num > 0:
    for i in range(1,num+1):
        factorial = factorial*i
print(factorial)

Enter the number :4
24


In [12]:
n = int(input("Enter the number :"))
dict = {}
for i in range (1,n+1):
    dict[i] = i*i
print(dict)
    
    #x = {print(i,i*i)}
    


Enter the number :5
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [4]:

def missing_char(x,y):
    x=x[0:y:]+x[y+1:]
    print(x)
missing_char("Arghad",3)
    

    

Argad


In [5]:
import numpy as np

In [6]:
x = np.arange(6).reshape(2,3)
print("original array :")
print(x)
print("Array to list : ")
print(x.tolist())



original array :
[[0 1 2]
 [3 4 5]]
Array to list : 
[[0, 1, 2], [3, 4, 5]]


In [11]:
array_1= np.array([0, 1, 2])
array_2 = np.array([2, 1, 0]) 
c = np.cov(array_1,array_2)
print(c)

[[ 1. -1.]
 [-1.  1.]]


In [33]:
import math
C = 50
H = 30
D = input("please enter the number ")
d_list = D.split(',')
for D in d_list:
    result = round(math.sqrt((2 * C * int(D))/H))
    print(result)


please enter the number 100,150
18
22
